### ISSUE TITLE
Typo in metadata field

### ISSUE THREAD

**Issue by sayangel** [petrbroz/forge-extract#1]
https://github.com/petrbroz/forge-extract/blob/58b11a22aa0e35a826ee8b72c4237b4e0336cd89/src/svf/deserialize.js#L107

`svf.metata` should be `svf.metadata`

**Comment by petrbroz** [comment]
Thanks @sayangel! Fixed in https://github.com/petrbroz/forge-extract/commit/0b41b4cb0debf5776d6d19a405e9addc3a6466bc.
