### ISSUE TITLE
accessor elements not of unit length errors

### ISSUE THREAD

**Issue by mazerab** [petrbroz/forge-extract#2]
This error is model specific. To reproduce translate to glTF provided model, then drag and drop the bin and gltf files into the free glTF viewer at https://gltf-viewer.donmccurdy.com/.

It will run a glTF validation script which reports this error.

![Screen Shot 2019-09-16 at 10 59 24](https://user-images.githubusercontent.com/15131317/64981592-3db9c680-d871-11e9-81a4-316d322be284.png)

**Comment by petrbroz** [comment]
It seems that in some cases, normals exported from SVF have non-unit length (e.g., 1.0002345), causing this glTF error. In commit https://github.com/petrbroz/forge-extract/commit/1ac8d42f12751684eff649fbb24b7cfd3eb92f4a I've added an explicit check that makes sure that normals have unit length.
