### ISSUE TITLE
Line support

### ISSUE THREAD

**Issue by wallabyway** [petrbroz/forge-extract#4]
I would like to see SVF's line data be available in glTF.

AEC models appear better. And tool paths are in lines which are useful for hololens.

**Comment by petrbroz** [comment]
https://github.com/petrbroz/forge-extract/tree/v0.2.0 has added basic support for colored lines & points.

**Comment by wallabyway** [comment]
does the "line data" come through the draco pipeline or Zeux pipeline?

**ie. with lines (from SVF/LMV viewer)**
![ice-stadium](https://user-images.githubusercontent.com/440241/70172623-ebc15980-1685-11ea-825f-27081353481a.jpg)

**Line data missing (glTF, zeux pipeline)**
![stadium2](https://user-images.githubusercontent.com/440241/71235962-8179fd00-22b2-11ea-8f11-dd8c28668251.jpg)
