### ISSUE TITLE
simple material support (non textures)

### ISSUE THREAD

**Issue by wallabyway** [petrbroz/forge-extract#5]
Low effort support for metal and plastic Fusion materials.  Just mapping the svf material to gltf  Roughness and metalness parameters.
(Textures support is not required)

**Comment by petrbroz** [comment]
The [typescript](https://github.com/petrbroz/forge-extract/tree/typescript) branch contains some initial support for generic ("SimplePhong") materials, also including textures but with no texture transforms.

**Comment by petrbroz** [comment]
The branch has been merged into master, so basic materials (and also textures) are now supported.
